### ISSUE TITLE
Passengers toggling the spotlight may not sync properly

### ISSUE THREAD

**Issue by michaelcerne** [michaelcerne/spotlight#3]

**Comment by Rubylium** [comment]
This is due to decor not being able to sync well if the player is not the entity owner

**Comment by michaelcerne** [comment]
[Related to this](https://forum.cfx.re/t/decor-update-sync-on-vehicles-while-there-is-a-driver-or-passenger/882079), looks like there isn't a good fix yet. Might just restrict spotlight operation to the entity owner.

**Comment by michaelcerne** [comment]
cf98926c71fc81a02c14a566021dbef25bcac0fa
