### ISSUE TITLE
emergency_only

### ISSUE THREAD

**Issue by Rubylium** [michaelcerne/spotlight#6]
emergency_only setting not working at all, you can toogle the spotlight in any vehicle

**Comment by Rubylium** [comment]
![image](https://user-images.githubusercontent.com/19718604/84570301-e8253280-ad8c-11ea-8fd6-316e975d426c.png)
As i can see here you do not check the setting value, i will try to do it but i'm not familiar with c#

**Comment by Rubylium** [comment]
Pretty sure the issue is here, it only pass the first if not the second if turret is enabled in settings
![image](https://user-images.githubusercontent.com/19718604/84600125-88f01c80-ae77-11ea-9cdf-97119947a233.png)

**Comment by michaelcerne** [comment]
Thanks for looking into it. I'll fix that.

**Comment by michaelcerne** [comment]
Fixed in aa066ac7e7325e45ae0d342cd609b8dcd704b37f
